/* tslint:disable */
/* eslint-disable */
/**
 * RESTFul接口示例
 * 此示例用于(interface_research)研究用, 包含不同种类的接口形态, 研究使用swagger规范生成客户端可执行代码
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请勿手动修改此文件.
 */
import {
    RecordProperty,
} from './';

export interface AddSomeRecordParam {
    /**
     * 属性分类
     * @type {number}
     */
    category: number;
    /**
     * record id
     * @type {string}
     */
    id: string;
    /**
     * 属性列表
     * @type {Array<RecordProperty>}
     */
    recordProperties: Array<RecordProperty>;
}
