/* tslint:disable */
/* eslint-disable */
/**
 * RESTFul接口示例
 * 此示例用于(interface_research)研究用, 包含不同种类的接口形态, 研究使用swagger规范生成客户端可执行代码
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请勿手动修改此文件.
 */

export interface RecordProperty {
    /**
     * 
     * @type {boolean}
     */
    enable?: boolean;
    /**
     * 
     * @type {string}
     */
    propertyName: string;
    /**
     * 类型, 枚举值: type1, type2, type3, 在实际业务场景中, 可以用String来代替
     * @type {string}
     */
    type: RecordPropertyTypeEnum;
    /**
     * 
     * @type {number}
     */
    value: number;
}

/**
* @export
* @enum {string}
*/
export enum RecordPropertyTypeEnum {
    Type1 = 'type1',
    Type2 = 'type2',
    Type3 = 'type3'
}
