/* tslint:disable */
/* eslint-disable */
/**
 * RESTFul接口示例
 * 此示例用于(interface_research)研究用, 包含不同种类的接口形态, 研究使用swagger规范生成客户端可执行代码
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请勿手动修改此文件.
 */

export interface UmsRole {
    /**
     * 后台用户数量
     * @type {number}
     */
    adminCount: number;
    /**
     * 创建时间
     * @type {Date}
     */
    createTime: Date;
    /**
     * 描述
     * @type {string}
     */
    description: string;
    /**
     * 
     * @type {number}
     */
    id: number;
    /**
     * 名称
     * @type {string}
     */
    name: string;
    /**
     * 
     * @type {number}
     */
    sort: number;
    /**
     * 启用状态：0->禁用；1->启用
     * @type {number}
     */
    status: number;
}
