/* tslint:disable */
/* eslint-disable */
/**
 * 后台系统接口
 * 后台相关接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请不要手动修改此文件.
 */


import {
    CommonResultOfLoginResponse,
    CommonResultOfLoginResponseFromJSON,
    CommonResultOfLoginResponseToJSON,
    CommonResultOfUmsAdmin,
    CommonResultOfUmsAdminFromJSON,
    CommonResultOfUmsAdminToJSON,
    CommonResultOfUmsAdminDetailData,
    CommonResultOfUmsAdminDetailDataFromJSON,
    CommonResultOfUmsAdminDetailDataToJSON,
    UmsAdminLoginParam,
    UmsAdminLoginParamFromJSON,
    UmsAdminLoginParamToJSON,
    UmsAdminParam,
    UmsAdminParamFromJSON,
    UmsAdminParamToJSON,
} from '../models';

export async function getAdminDetailInfoUsingGET() {

}
    async getAdminDetailInfoUsingGET(username: string): Promise<CommonResultOfUmsAdminDetailData> {
        const response = await this.getAdminDetailInfoUsingGETRaw({ username: username });
        return await response.value();
    }
export async function getAdminInfoUsingGET() {

}
    async getAdminInfoUsingGET(userId: string): Promise<CommonResultOfUmsAdmin> {
        const response = await this.getAdminInfoUsingGETRaw({ userId: userId });
        return await response.value();
    }
export async function loginUsingPOST() {

}
    async loginUsingPOST(umsAdminLoginParam: UmsAdminLoginParam): Promise<CommonResultOfLoginResponse> {
        const response = await this.loginUsingPOSTRaw({ umsAdminLoginParam: umsAdminLoginParam });
        return await response.value();
    }
export async function registerUsingPOST() {

}
    async registerUsingPOST(umsAdminParam: UmsAdminParam): Promise<CommonResultOfUmsAdmin> {
        const response = await this.registerUsingPOSTRaw({ umsAdminParam: umsAdminParam });
        return await response.value();
    }
