/* tslint:disable */
/* eslint-disable */
/**
 * 后台系统接口
 * 后台相关接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请不要手动修改此文件.
 */


export interface LoginResponse {
    /**
     * 
     * @type {string}
     */
    token?: string;
    /**
     * 
     * @type {string}
     */
    tokenHead?: string;
    /**
     * 
     * @type {string}
     */
    tokenType?: LoginResponseTokenTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum LoginResponseTokenTypeEnum {
    Type1 = 'type1',
    Type2 = 'type2'
}
