/* tslint:disable */
/* eslint-disable */
/**
 * 后台系统接口
 * 后台相关接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请不要手动修改此文件.
 */


export interface UmsAdmin {
    /**
     * 创建时间
     * @type {Date}
     */
    createTime: Date;
    /**
     * 邮箱
     * @type {string}
     */
    email: string;
    /**
     * 头像
     * @type {string}
     */
    icon: string;
    /**
     * 
     * @type {number}
     */
    id: number;
    /**
     * 最后登录时间
     * @type {Date}
     */
    loginTime: Date;
    /**
     * 昵称
     * @type {string}
     */
    nickName: string;
    /**
     * 备注信息
     * @type {string}
     */
    note: string;
    /**
     * 
     * @type {string}
     */
    password: string;
    /**
     * 帐号启用状态：0->禁用；1->启用
     * @type {number}
     */
    status: number;
    /**
     * 
     * @type {string}
     */
    username: string;
}
