/* tslint:disable */
/* eslint-disable */
/**
 * 后台系统接口
 * 后台相关接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请不要手动修改此文件.
 */


export interface UmsRole {
    /**
     * 后台用户数量
     * @type {number}
     */
    adminCount: number;
    /**
     * 创建时间
     * @type {Date}
     */
    createTime: Date;
    /**
     * 描述
     * @type {string}
     */
    description: string;
    /**
     * 
     * @type {number}
     */
    id: number;
    /**
     * 名称
     * @type {string}
     */
    name: string;
    /**
     * 
     * @type {number}
     */
    sort: number;
    /**
     * 启用状态：0->禁用；1->启用
     * @type {number}
     */
    status: number;
}
