/* tslint:disable */
/* eslint-disable */
/**
 * RESTFul接口示例
 * 此示例用于(interface_research)研究用, 包含不同种类的接口形态, 研究使用swagger规范生成客户端可执行代码
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * 请勿手动修改此文件.
 */

import axios from '../request'

import {
    CommonResultOfLoginResponse,
    CommonResultOfUmsAdmin,
    CommonResultOfUmsAdminDetailData,
    UmsAdminLoginParam,
    UmsAdminParam,
} from '../models';

export interface GetAdminInfoUsingGETRequest {
  userId: string;
}


/**
 * 获取用户详细信息
 */
export async function getAdminDetailInfoUsingGET(
  /** username */
  username: string
): Promise<CommonResultOfUmsAdminDetailData> {
  return axios({
    url: `/admin/user_detail_info/{username}`.replace(`{${"username"}}`, encodeURIComponent(String(username))),
    method: 'GET',
  })
}

/**
 * 获取用户信息
 */
export async function getAdminInfoUsingGET(
  params: GetAdminInfoUsingGETRequest
): Promise<CommonResultOfUmsAdmin> {
  return axios({
    url: `/admin/user_info`,
    method: 'GET',
    params,
  })
}

/**
 * 登录以后返回token
 */
export async function loginUsingPOST(
  bodyData: UmsAdminLoginParam
): Promise<CommonResultOfLoginResponse> {
  return axios({
    url: `/admin/login`,
    method: 'POST',
    data: bodyData,
  })
}

/**
 * 用户注册
 */
export async function registerUsingPOST(
  bodyData: UmsAdminParam
): Promise<CommonResultOfUmsAdmin> {
  return axios({
    url: `/admin/register`,
    method: 'POST',
    data: bodyData,
  })
}

